const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const INTERNAL_SERVER_ERROR = 500;
const DUPLICATE_KEY_ERROR = 409;

module.exports = {
  NOT_FOUND, BAD_REQUEST, INTERNAL_SERVER_ERROR, DUPLICATE_KEY_ERROR,
};
